music.setVolume(255)
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(466, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(466, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Double))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Breve))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Double))
music.playTone(523, music.beat(BeatFraction.Breve))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Double))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Double))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Double))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Eighth))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))